Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt update -y 
        apt install -y docker.io docker-compose
    SHELL
end